const path = require("path");
const crypto = require("crypto");
const express = require("express");
const multer = require("multer");
const { requireAdmin } = require("../middleware/auth");

const router = express.Router();

const ALLOWED_CATEGORIES = new Set([
  "grievance-attachments",
  "grievance-acknowledgements",
  "grievance-videos",
  "complaint-supporting",
  "complaint-leader-photos",
  "social-media-files",
]);

const MAX_FILE_BYTES = 20 * 1024 * 1024; // 20MB

const storage = multer.diskStorage({
  destination: (req, _file, cb) => {
    const category = req.params.category;
    cb(null, path.join(process.env.UPLOAD_DIR || "uploads", category));
  },
  filename: (_req, file, cb) => {
    const ext = path.extname(file.originalname);
    cb(null, `${Date.now()}_${crypto.randomBytes(8).toString("hex")}${ext}`);
  },
});

const upload = multer({ storage, limits: { fileSize: MAX_FILE_BYTES } });

function requireValidCategory(req, res, next) {
  if (!ALLOWED_CATEGORIES.has(req.params.category)) {
    return res.status(404).json({ error: "Unknown upload category" });
  }
  next();
}

// POST /api/uploads/:category — public (anonymous citizens attach files to
// their own submission before it's inserted), returns a path to store on
// the submission row. The files themselves are only ever served back out
// through GET, which is admin-only — see below.
router.post("/:category", requireValidCategory, upload.single("file"), (req, res) => {
  if (!req.file) return res.status(400).json({ error: "No file uploaded" });
  res.status(201).json({
    path: `${req.params.category}/${req.file.filename}`,
  });
});

// GET /api/uploads/:category/:filename — admin only, matches the intent of
// the old Supabase Storage policies (public can upload, only admins can
// read attachments back).
router.get(
  "/:category/:filename",
  requireValidCategory,
  requireAdmin,
  (req, res) => {
    // filenames are always generated by multer on upload (timestamp + hex),
    // but this is a user-supplied URL param, so reject anything that isn't
    // a bare filename before it ever touches the filesystem.
    if (req.params.filename !== path.basename(req.params.filename)) {
      return res.status(400).json({ error: "Invalid filename" });
    }
    const filePath = path.join(
      process.env.UPLOAD_DIR || "uploads",
      req.params.category,
      req.params.filename
    );
    res.sendFile(path.resolve(filePath), (err) => {
      if (err) res.status(404).json({ error: "File not found" });
    });
  }
);

module.exports = router;
